version: "3.9"

services:
  kafka-01:
    image: bitnami/kafka:3.2.0
    environment:
      KAFKA_ENABLE_KRAFT: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: INTERNAL://kafka-01:9092,EXTERNAL://:9093,CONTROLLER://kafka-01:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-01:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKA_KRAFT_CLUSTER_ID: WSxyUqJ9TVmF93BCS21HMg
      BITNAMI_DEBUG: 1
    ports:
      - 9093:9093
    volumes:
      - ./data/kafka-01:/bitnami/kafka
    networks:
      - walletd
    container_name: wallet-kafka-01

  kafka-02:
    image: bitnami/kafka:3.2.0
    environment:
      KAFKA_ENABLE_KRAFT: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: INTERNAL://kafka-02:9092,EXTERNAL://:9094,CONTROLLER://kafka-02:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-02:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKA_KRAFT_CLUSTER_ID: WSxyUqJ9TVmF93BCS21HMg
      BITNAMI_DEBUG: 1
    ports:
      - 9094:9094
    volumes:
      - ./data/kafka-02:/bitnami/kafka
    networks:
      - walletd
    container_name: wallet-kafka-02
  
  kafka-03:
    image: bitnami/kafka:3.2.0
    environment:
      KAFKA_ENABLE_KRAFT: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: INTERNAL://kafka-03:9092,EXTERNAL://:9095,CONTROLLER://kafka-03:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-03:9092,EXTERNAL://localhost:9095
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091,2@kafka-02:9091,3@kafka-03:9091
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKA_KRAFT_CLUSTER_ID: WSxyUqJ9TVmF93BCS21HMg
      BITNAMI_DEBUG: 1
    ports:
      - 9095:9095
    volumes:
      - ./data/kafka-03:/bitnami/kafka
    networks:
      - walletd
    container_name: wallet-kafka-03

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: kafka-01:9092,kafka-02:9092,kafka-03:9092
    ports:
      - 9000:9000
    depends_on:
      - kafka-01
      - kafka-02
      - kafka-03
    networks:
      - walletd
    container_name: wallet-kafdrop

  elastic-01:
    image: elasticsearch:8.2.2
    environment:
      - node.name=elastic-01
      - cluster.name=wallet-cluster
      - discovery.seed_hosts=elastic-02,elastic-03
      - cluster.initial_master_nodes=elastic-01,elastic-02,elastic-03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic-01:/usr/share/elasticsearch/data
    networks:
      - walletd
    container_name: wallet-elastic-01
  
  elastic-02:
    image: elasticsearch:8.2.2
    environment:
      - node.name=elastic-02
      - cluster.name=wallet-cluster
      - discovery.seed_hosts=elastic-01,elastic-03
      - cluster.initial_master_nodes=elastic-01,elastic-02,elastic-03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9201:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic-02:/usr/share/elasticsearch/data
    networks:
      - walletd
    container_name: wallet-elastic-02

  elastic-03:
    image: elasticsearch:8.2.2
    environment:
      - node.name=elastic-03
      - cluster.name=wallet-cluster
      - discovery.seed_hosts=elastic-01,elastic-02
      - cluster.initial_master_nodes=elastic-01,elastic-02,elastic-03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9202:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic-03:/usr/share/elasticsearch/data
    networks:
      - walletd
    container_name: wallet-elastic-03

  kibana:
    image: kibana:8.2.2
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic-01:9200","http://elastic-02:9200","http://elastic-03:9200"]'
    ports:
      - 5601:5601
    networks:
      - walletd
    container_name: wallet-kibana

  eventstore-01:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=false
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1

      - EVENTSTORE_INT_IP=172.30.240.11
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2111
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1111
      - EVENTSTORE_GOSSIP_SEED=172.30.240.12:2113,172.30.240.13:2113
    ports:
      - 1111:1113
      - 2111:2113
    volumes:
      - ./data/eventstore-01/data:/var/lib/eventstore
      - ./data/eventstore-01/logs:/var/log/eventstore
    networks:
      walletd:
        ipv4_address: 172.30.240.11
    container_name: wallet-eventstore-01

  eventstore-02:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=false
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1

      - EVENTSTORE_INT_IP=172.30.240.12
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2112
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1112
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.13:2113
    ports:
      - 1112:1113
      - 2112:2113
    volumes:
      - ./data/eventstore-02/data:/var/lib/eventstore
      - ./data/eventstore-02/logs:/var/log/eventstore
    networks:
      walletd:
        ipv4_address: 172.30.240.12
    container_name: wallet-eventstore-02
  
  eventstore-03:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DISCOVER_VIA_DNS=false
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1

      - EVENTSTORE_INT_IP=172.30.240.13
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
      - EVENTSTORE_GOSSIP_SEED=172.30.240.11:2113,172.30.240.12:2113
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - ./data/eventstore-03/data:/var/lib/eventstore
      - ./data/eventstore-03/logs:/var/log/eventstore
    networks:
      walletd:
        ipv4_address: 172.30.240.13
    container_name: wallet-eventstore-03

networks:
  walletd:
    ipam:
      driver: default
      config:
        - subnet: 172.30.240.0/24
    name: walletd
